services:
  redis:
    image: redis:alpine
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "6379:6379"

  app:
    build: .
    # volumes:
    #    - ./ratelimiter/.env:/app/.env
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: ""
      APP_PORT: "8080"
    depends_on:
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1
